# Generated by Django 2.2.12 on 2020-05-17 12:42

from django.db import migrations
from django.utils.text import slugify

def forwards_func(apps, schema_editor):
    pro_cat_model = apps.get_model("mainapp", "ProductCategory")
    pro_model = apps.get_model("mainapp", "Products")

    # Create new category
    pro_cat_obj = pro_cat_model.objects.create(
        pk=1,
        name="\u0416\u0435\u043d\u0441\u043a\u0430\u044f \u043e\u0434\u0435\u0436\u0434\u0430",
        slug="zhenskaya-odezhda",
    )
    pro_model.objects.create(
        pk=1,
        category=pro_cat_obj,
        title="New Woman Wearing Dress",
        slug="new-woman-wearing-dress",
        content="1 A small river named Duden flows by their place and supplies it with the necessary regelialia. "
                "It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n\r\n<p>"
                "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would "
                "have been rewritten a thousand times and everything that was left from its origin would be the word "
                "&quot;and&quot; and the Little Blind Text should turn around and return to its own, safe country. But "
                "nothing the copy said could convince her and so it didn&rsquo;t take long until a few insidious Copy "
                "Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where "
                "they abused her for their.",
        created_at="2020-05-13T16:55:01.255Z",
        photo="products_images/product-1.jpg",
        price=120.00,
        quantity=10
    )
    pro_model.objects.create(
        pk=2,
        category=pro_cat_obj,
        title="Old Woman Wearing Dress",
        slug="old-woman-wearing-dress",
        content="2 A small river named Duden flows by their place and supplies it with the necessary regelialia. "
                "It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n\r\n<p>"
                "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would "
                "have been rewritten a thousand times and everything that was left from its origin would be the word "
                "&quot;and&quot; and the Little Blind Text should turn around and return to its own, safe country. But "
                "nothing the copy said could convince her and so it didn&rsquo;t take long until a few insidious Copy "
                "Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where "
                "they abused her for their.",
        created_at="2020-05-13T16:55:01.255Z",
        photo="products_images/product-2.jpg",
        price=220.00,
        quantity=10
    )
    pro_model.objects.create(
        pk=3,
        category=pro_cat_obj,
        title="Night Woman Wearing Dress",
        slug="night-woman-wearing-dress",
        content="3 A small river named Duden flows by their place and supplies it with the necessary regelialia. "
                "It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n\r\n<p>"
                "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would "
                "have been rewritten a thousand times and everything that was left from its origin would be the word "
                "&quot;and&quot; and the Little Blind Text should turn around and return to its own, safe country. But "
                "nothing the copy said could convince her and so it didn&rsquo;t take long until a few insidious Copy "
                "Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where "
                "they abused her for their.",
        created_at="2020-05-13T16:55:01.255Z",
        photo="products_images/product-3.jpg",
        price=320.00,
        quantity=10
    )
    pro_model.objects.create(
        pk=4,
        category=pro_cat_obj,
        title="Mini Woman Wearing Dress",
        slug="mini-woman-wearing-dress",
        content="4 A small river named Duden flows by their place and supplies it with the necessary regelialia. "
                "It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n\r\n<p>"
                "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would "
                "have been rewritten a thousand times and everything that was left from its origin would be the word "
                "&quot;and&quot; and the Little Blind Text should turn around and return to its own, safe country. But "
                "nothing the copy said could convince her and so it didn&rsquo;t take long until a few insidious Copy "
                "Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where "
                "they abused her for their.",
        created_at="2020-05-13T16:55:01.255Z",
        photo="products_images/product-4.jpg",
        price=420.00,
        quantity=10
    )
    pro_model.objects.create(
        pk=5,
        category=pro_cat_obj,
        title="Orange Woman Wearing Dress",
        slug="orange-woman-wearing-dress",
        content="5 A small river named Duden flows by their place and supplies it with the necessary regelialia. "
                "It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n\r\n<p>"
                "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would "
                "have been rewritten a thousand times and everything that was left from its origin would be the word "
                "&quot;and&quot; and the Little Blind Text should turn around and return to its own, safe country. But "
                "nothing the copy said could convince her and so it didn&rsquo;t take long until a few insidious Copy "
                "Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where "
                "they abused her for their.",
        created_at="2020-05-13T16:55:01.255Z",
        photo="products_images/product-5.jpg",
        price=520.00,
        quantity=40
    )
    pro_model.objects.create(
        pk=6,
        category=pro_cat_obj,
        title="Red Woman Wearing Dress",
        slug="red-woman-wearing-dress",
        content="6 A small river named Duden flows by their place and supplies it with the necessary regelialia. "
                "It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n\r\n<p>"
                "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would "
                "have been rewritten a thousand times and everything that was left from its origin would be the word "
                "&quot;and&quot; and the Little Blind Text should turn around and return to its own, safe country. But "
                "nothing the copy said could convince her and so it didn&rsquo;t take long until a few insidious Copy "
                "Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where "
                "they abused her for their.",
        created_at="2020-05-13T16:55:01.255Z",
        photo="products_images/product-6.jpg",
        price=620.00,
        quantity=15
    )
    pro_model.objects.create(
        pk=7,
        category=pro_cat_obj,
        title="Black Woman Wearing Dress",
        slug="black-woman-wearing-dress",
        content="7 A small river named Duden flows by their place and supplies it with the necessary regelialia. "
                "It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n\r\n<p>"
                "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would "
                "have been rewritten a thousand times and everything that was left from its origin would be the word "
                "&quot;and&quot; and the Little Blind Text should turn around and return to its own, safe country. But "
                "nothing the copy said could convince her and so it didn&rsquo;t take long until a few insidious Copy "
                "Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where "
                "they abused her for their.",
        created_at="2020-05-13T16:55:01.255Z",
        photo="products_images/product-7.jpg",
        price=720.00,
        quantity=60
    )
    del pro_cat_obj
    pro_cat_obj = pro_cat_model.objects.create(
        pk=2,
        name="Мужская одежда",
        slug="man-odezhda",
    )
    pro_model.objects.create(
        pk=10,
        category=pro_cat_obj,
        title="Man Wearing Dress",
        slug="man-wearing-dress",
        content="A small river named Duden flows by their place and supplies it with the necessary regelialia. "
                "It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n\r\n<p>"
                "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would "
                "have been rewritten a thousand times and everything that was left from its origin would be the word "
                "&quot;and&quot; and the Little Blind Text should turn around and return to its own, safe country. But "
                "nothing the copy said could convince her and so it didn&rsquo;t take long until a few insidious Copy "
                "Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where "
                "they abused her for their.",
        created_at="2020-05-17T16:55:01.255Z",
        photo="products_images/product-8.jpg",
        price=1930.00,
        quantity=11
    )
    del pro_cat_obj


def reverse_func(apps, schema_editor):
    pro_cat_model = apps.get_model("mainapp", "ProductCategory")
    pro_cat_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
